"""adjust table

Revision ID: cd785ebacbe1
Revises: e527a2599069
Create Date: 2023-10-30 16:56:55.263179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd785ebacbe1'
down_revision = 'e527a2599069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_trips', schema=None) as batch_op:
        batch_op.drop_column('end_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.DATE(), nullable=False))

    # ### end Alembic commands ###
